language: c

compiler:
   - gcc

os:
   - linux

install:
   - git clone https://github.com/google/googletest
   - cd googletest
   - cmake .
   - make
   - sudo cp googlemock/gtest/libgtest.a /usr/lib
   - sudo cp googlemock/gtest/libgtest_main.a /usr/lib
   - sudo cp -R googletest/include/gtest /usr/include/
   - cd "${TRAVIS_BUILD_DIR}"
